name: build-docker-container

on:
  workflow_run:
    types: [completed]
    workflow: [build-and-test]
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-docker-container:
    strategy:
      matrix:
        platform: [linux/arm/v7, linux/amd64]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: ${{ matrix.platform }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push the Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: ${{ matrix.platform }}
          tags: |
            ghcr.io/dilaz/gdqbot:latest
            ghcr.io/dilaz/gdqbot:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
